version: "2"
services:
  client:
    build:
      context: ./client
    ports:
      - "3400:3000"
    volumes:
      - ./client:/client
  server:
    build:
      context: ./server
    command: yarn run watch
    environment:
      - PORT=3100
    ports:
      - "3300:3100"
    volumes:
      - ./server:/server
  elasticsearch:
    build: ./docker-containers/elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-plugins:/usr/share/elasticsearch/plugins
    environment:
      - cluster.name=expense-explorer-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1024m
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - server
  dejavu:
    image: appbaseio/dejavu:3.0.0-alpha
    ports:
      - 1358:1358
    depends_on:
      - elasticsearch
