version: "2"
services:
  client:
    build:
      context: ./client
    ports:
      - "3400:3000"
    volumes:
      - ./client:/client
  server:
    build:
      context: ./server
    command: yarn run watch
    environment:
      - PORT=3100
    ports:
      - "3300:3100"
    volumes:
      - ./server:/server
